# NEW AND CORRECTED VERSION
services:
  - type: web
    name: telegram-job-bot
    plan: free 
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6